m1=int(input("Enter marks for student number 1:"))
m2=int(input("Enter marks for student number 2:"))
m3=int(input("Enter marks for student number 3:"))
m4=int(input("Enter marks for student number 4:"))
m5=int(input("Enter marks for student number 5:"))
m6=int(input("Enter marks for student number 6:"))
m7=int(input("Enter marks for student number 7:"))
mymarkslist=[m1,m2,m3,m4,m5,m6,m7]
print(mymarkslist)
mymarkslist.sort()
print(mymarkslist)